lib/s390x/io: Make sure that exit() is not returning
Since commit 96d79976f779589 kvm-unit-tests can not be compiled on
s390x anymore. The compiler complains:

lib/s390x/io.c: In function â€˜exitâ€™:
lib/s390x/io.c:57:1: error: â€˜noreturnâ€™ function does return [-Werror]

Let's make sure that the function can really not return anymore
(i.e. also do not return anymore in case SIGP is broken for example).

Fixes: 96d79976f779589bbdbb24474de8fd214b179d7e
Reported-by: LukÃ¡Å¡ Doktor <ldoktor@redhat.com>
Signed-off-by: Thomas Huth <thuth@redhat.com>
Message-Id: <1537858200-15083-1-git-send-email-thuth@redhat.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>