x86/pmu: Fix compilation on macOS
Compiling for i686 on macOS in the CI currently fails with:

.../cirrus-ci-build/x86/pmu.c: In function 'main':
.../cirrus-ci-build/x86/pmu.c:1012:41: error: format '%x' expects argument of
 type 'unsigned int', but argument 2 has type 'u32' {aka 'long unsigned int'}
 [-Werror=format=]
 1012 |     printf("Arch Events (mask):  0x%x\n", pmu.arch_event_available);
      |                                    ~^     ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |        |
      |                                     |        u32 {aka long unsigned int}
      |                                     unsigned int
      |                                    %lx

Use the correct format string for u32 to fix this issue.

Fixes: 92dc5f7a ("x86/pmu: Mark Intel architectural event available [...]")
Signed-off-by: Thomas Huth <thuth@redhat.com>
Message-ID: <20250723164742.1174289-1-thuth@redhat.com>