realmode: load above stack
The bottom 32K of memory are generally reserved for use by the BIOS;
for example, traditionally the boot loader is placed at 0x7C00 and
the stack grows below that address.

It turns out that with some versions of clang, realmode.flat has
become big enough that it overlaps the stack used by the multiboot
option ROM loader.  The result is that a couple instructions are
overwritten.  Typically one or two tests fail and that's it...

Move the code above the forbidden region, in real 90s style.

Additionally, we've got to compile the test with -Os now, otherwise
the code might get too big when compiling with older versions of clang
(e.g. Clang v20), so linking fails with:

 x86/realmode.o: In function `realmode_start':
 realmode.c:(.text+0x79): relocation truncated to fit: R_386_16 against `.bss'
 realmode.c:(.text+0x82): relocation truncated to fit: R_386_16 against `.bss'
 realmode.c:(.text+0x8b): relocation truncated to fit: R_386_16 against `.bss'
 realmode.c:(.text+0x94): relocation truncated to fit: R_386_16 against `.bss'

Unfortunately, the -Os triggers compiler warnings in this code
with GCC v16:

 In function ‘test_int’,
     inlined from ‘realmode_start’ at x86/realmode.c:1781:2:
 x86/realmode.c:828:28: error: array subscript 0 is outside array bounds
  of ‘u32[0]’ {aka ‘unsigned int[]’} [-Werror=array-bounds=]
   828 |         *(u32 *)(0x11 * 4) = 0x1000; /* Store a pointer to address 0x1000 in IDT entry 0x11 */
       |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~
 In function ‘realmode_start’:
 cc1: note: source object is likely at address zero
 In function ‘test_sti_inhibit’,
     inlined from ‘realmode_start’ at x86/realmode.c:1782:2:
 x86/realmode.c:841:28: error: array subscript 0 is outside array bounds
  of ‘u32[0]’ {aka ‘unsigned int[]’} [-Werror=array-bounds=]
   841 |         *(u32 *)(0x73 * 4) = 0x1000; /* Store IRQ 11 handler in the IDT */
       |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~
 In function ‘realmode_start’:
 cc1: note: source object is likely at address zero
 cc1: all warnings being treated as errors

... so additionally we also have to compile this test with this warning
disabled now.

Reported-by: Thomas Huth <thuth@redhat.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
Message-ID: <20240604143507.1041901-1-pbonzini@redhat.com>
[thuth: Add -Os and -Wno-array-bounds to CFLAGS to avoid other problems]
Signed-off-by: Thomas Huth <thuth@redhat.com>
Message-ID: <20260506130642.2571332-1-thuth@redhat.com>