x86: fix build (macro R interpreted as raw string)
GCC 5.0.0 enables raw strings by default and they have higher priority
than macros, thus R"[...]" is interpreted incorrectly:

  lib/x86/isr.c:112:30: error: invalid character ')' in raw string delimiter
  lib/x86/isr.c:112:8: error: stray ‘R’ in program
  lib/x86/isr.c:112:26: error: expected ‘:’ or ‘)’ before string constant
          "orl $0x200, (%%"R"sp)\n\t"

Fix it by putting a space between macro R and a string literal.
(We already do that somewhere.)

Signed-off-by: Radim Krčmář <rkrcmar@redhat.com>
Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>