fix printf warning on 32-bit macOS
uint32_t is "unsigned long" on 32-bit macOS, which causes a warning
if it is passed to printf as %d:

/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/lib/libcflat.h:141:24: error: format '%d' expects argument of type int, but argument 6 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  141 |                 printf("%s:%d: assert failed: %s: " fmt "\n",           \
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/lib/x86/processor.h:460:9: note: in expansion of macro 'assert_msg'
  460 |         assert_msg(!vector, "Unexpected %s on RDPMC(%d)",
      |         ^~~~~~~~~~

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>